import { FuturesAsset } from '../types/futures';

export const INITIAL_FUTURES_ASSETS: FuturesAsset[] = [
  // --- CRYPTO FUTURES (20X) ---
  {
    id: 'fut_btc',
    name: 'Bitcoin (20X Futures)',
    symbol: 'BTC/USDT',
    tvSymbol: 'BINANCE:BTCUSDT',
    category: 'Crypto',
    price: 79950.00,
    change24h: 2.85,
    leverage: 20,
    minMargin: 100,
    maxMargin: 50000,
    takerFeePercent: 0.05,
    precision: 2,
    currencySymbol: '$',
  },
  {
    id: 'fut_eth',
    name: 'Ethereum (20X Futures)',
    symbol: 'ETH/USDT',
    tvSymbol: 'BINANCE:ETHUSDT',
    category: 'Crypto',
    price: 2495.50,
    change24h: 3.12,
    leverage: 20,
    minMargin: 100,
    maxMargin: 50000,
    takerFeePercent: 0.05,
    precision: 2,
    currencySymbol: '$',
  },
  {
    id: 'fut_sol',
    name: 'Solana (20X Futures)',
    symbol: 'SOL/USDT',
    tvSymbol: 'BINANCE:SOLUSDT',
    category: 'Crypto',
    price: 106.80,
    change24h: 5.40,
    leverage: 20,
    minMargin: 100,
    maxMargin: 50000,
    takerFeePercent: 0.05,
    precision: 2,
    currencySymbol: '$',
  },
  {
    id: 'fut_bnb',
    name: 'Binance Coin (20X Futures)',
    symbol: 'BNB/USDT',
    tvSymbol: 'BINANCE:BNBUSDT',
    category: 'Crypto',
    price: 756.20,
    change24h: 1.80,
    leverage: 20,
    minMargin: 100,
    maxMargin: 50000,
    takerFeePercent: 0.05,
    precision: 2,
    currencySymbol: '$',
  },
  {
    id: 'fut_xrp',
    name: 'Ripple (20X Futures)',
    symbol: 'XRP/USDT',
    tvSymbol: 'BINANCE:XRPUSDT',
    category: 'Crypto',
    price: 1.4180,
    change24h: 4.25,
    leverage: 20,
    minMargin: 100,
    maxMargin: 50000,
    takerFeePercent: 0.05,
    precision: 4,
    currencySymbol: '$',
  },
  {
    id: 'fut_doge',
    name: 'Dogecoin (20X Futures)',
    symbol: 'DOGE/USDT',
    tvSymbol: 'BINANCE:DOGEUSDT',
    category: 'Crypto',
    price: 0.08960,
    change24h: -0.95,
    leverage: 20,
    minMargin: 100,
    maxMargin: 50000,
    takerFeePercent: 0.05,
    precision: 5,
    currencySymbol: '$',
  },
  {
    id: 'fut_ada',
    name: 'Cardano (20X Futures)',
    symbol: 'ADA/USDT',
    tvSymbol: 'BINANCE:ADAUSDT',
    category: 'Crypto',
    price: 0.3840,
    change24h: 1.15,
    leverage: 20,
    minMargin: 100,
    maxMargin: 50000,
    takerFeePercent: 0.05,
    precision: 4,
    currencySymbol: '$',
  },

  // --- FOREX FUTURES (20X) ---
  {
    id: 'fut_eurusd',
    name: 'EUR / USD (20X Futures)',
    symbol: 'EUR/USD',
    tvSymbol: 'FX:EURUSD',
    category: 'Forex',
    price: 1.0845,
    change24h: 0.22,
    leverage: 20,
    minMargin: 100,
    maxMargin: 50000,
    takerFeePercent: 0.04,
    precision: 4,
    currencySymbol: '$',
  },
  {
    id: 'fut_gbpusd',
    name: 'GBP / USD (20X Futures)',
    symbol: 'GBP/USD',
    tvSymbol: 'FX:GBPUSD',
    category: 'Forex',
    price: 1.2980,
    change24h: 0.35,
    leverage: 20,
    minMargin: 100,
    maxMargin: 50000,
    takerFeePercent: 0.04,
    precision: 4,
    currencySymbol: '$',
  },
  {
    id: 'fut_usdjpy',
    name: 'USD / JPY (20X Futures)',
    symbol: 'USD/JPY',
    tvSymbol: 'FX:USDJPY',
    category: 'Forex',
    price: 152.65,
    change24h: -0.18,
    leverage: 20,
    minMargin: 100,
    maxMargin: 50000,
    takerFeePercent: 0.04,
    precision: 2,
    currencySymbol: '¥',
  },
  {
    id: 'fut_usdinr',
    name: 'USD / INR (20X Futures)',
    symbol: 'USD/INR',
    tvSymbol: 'FX_IDC:USDINR',
    category: 'Forex',
    price: 86.82,
    change24h: 0.08,
    leverage: 20,
    minMargin: 100,
    maxMargin: 50000,
    takerFeePercent: 0.03,
    precision: 2,
    currencySymbol: '₹',
  },
  {
    id: 'fut_audusd',
    name: 'AUD / USD (20X Futures)',
    symbol: 'AUD/USD',
    tvSymbol: 'FX:AUDUSD',
    category: 'Forex',
    price: 0.6580,
    change24h: -0.42,
    leverage: 20,
    minMargin: 100,
    maxMargin: 50000,
    takerFeePercent: 0.04,
    precision: 4,
    currencySymbol: '$',
  },
  {
    id: 'fut_gbpjpy',
    name: 'GBP / JPY (20X Futures)',
    symbol: 'GBP/JPY',
    tvSymbol: 'FX:GBPJPY',
    category: 'Forex',
    price: 198.15,
    change24h: 0.45,
    leverage: 20,
    minMargin: 100,
    maxMargin: 50000,
    takerFeePercent: 0.04,
    precision: 2,
    currencySymbol: '¥',
  },

  // --- INDIAN MARKETS FUTURES (20X) ---
  {
    id: 'fut_nifty',
    name: 'NIFTY 50 (20X Futures)',
    symbol: 'NIFTY',
    tvSymbol: 'NSE:NIFTY',
    category: 'Indian',
    price: 24535.80,
    change24h: 0.68,
    leverage: 20,
    minMargin: 100,
    maxMargin: 50000,
    takerFeePercent: 0.05,
    precision: 2,
    currencySymbol: '₹',
  },
  {
    id: 'fut_banknifty',
    name: 'BANK NIFTY (20X Futures)',
    symbol: 'BANKNIFTY',
    tvSymbol: 'NSE:BANKNIFTY',
    category: 'Indian',
    price: 51240.50,
    change24h: 0.94,
    leverage: 20,
    minMargin: 100,
    maxMargin: 50000,
    takerFeePercent: 0.05,
    precision: 2,
    currencySymbol: '₹',
  },
  {
    id: 'fut_reliance',
    name: 'Reliance Industries (20X)',
    symbol: 'RELIANCE',
    tvSymbol: 'NSE:RELIANCE',
    category: 'Indian',
    price: 2958.40,
    change24h: 1.45,
    leverage: 20,
    minMargin: 100,
    maxMargin: 50000,
    takerFeePercent: 0.05,
    precision: 2,
    currencySymbol: '₹',
  },
  {
    id: 'fut_tatamotors',
    name: 'Tata Motors (20X Futures)',
    symbol: 'TATAMOTORS',
    tvSymbol: 'NSE:TATAMOTORS',
    category: 'Indian',
    price: 985.20,
    change24h: 2.10,
    leverage: 20,
    minMargin: 100,
    maxMargin: 50000,
    takerFeePercent: 0.05,
    precision: 2,
    currencySymbol: '₹',
  },
  {
    id: 'fut_hdfcbank',
    name: 'HDFC Bank (20X Futures)',
    symbol: 'HDFCBANK',
    tvSymbol: 'NSE:HDFCBANK',
    category: 'Indian',
    price: 1642.75,
    change24h: -0.35,
    leverage: 20,
    minMargin: 100,
    maxMargin: 50000,
    takerFeePercent: 0.05,
    precision: 2,
    currencySymbol: '₹',
  },
  {
    id: 'fut_infosys',
    name: 'Infosys (20X Futures)',
    symbol: 'INFY',
    tvSymbol: 'NSE:INFY',
    category: 'Indian',
    price: 1890.30,
    change24h: 0.85,
    leverage: 20,
    minMargin: 100,
    maxMargin: 50000,
    takerFeePercent: 0.05,
    precision: 2,
    currencySymbol: '₹',
  },

  // --- COMMODITIES FUTURES (20X) ---
  {
    id: 'fut_gold',
    name: 'Gold (XAU/USD - 20X)',
    symbol: 'GOLD',
    tvSymbol: 'TVC:GOLD',
    category: 'Commodities',
    price: 2684.50,
    change24h: 0.54,
    leverage: 20,
    minMargin: 100,
    maxMargin: 50000,
    takerFeePercent: 0.04,
    precision: 2,
    currencySymbol: '$',
  },
  {
    id: 'fut_silver',
    name: 'Silver (XAG/USD - 20X)',
    symbol: 'SILVER',
    tvSymbol: 'TVC:SILVER',
    category: 'Commodities',
    price: 31.85,
    change24h: 1.15,
    leverage: 20,
    minMargin: 100,
    maxMargin: 50000,
    takerFeePercent: 0.04,
    precision: 2,
    currencySymbol: '$',
  },
  {
    id: 'fut_crude',
    name: 'Crude Oil (WTI - 20X)',
    symbol: 'CRUDEOIL',
    tvSymbol: 'TVC:USOIL',
    category: 'Commodities',
    price: 71.40,
    change24h: -0.75,
    leverage: 20,
    minMargin: 100,
    maxMargin: 50000,
    takerFeePercent: 0.04,
    precision: 2,
    currencySymbol: '$',
  },
];
